// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyuEzBrb9ZA_2Jrse2XD9yBqBGIVRR2us',
    appId: '1:1068838387571:web:2ab6a4f631bb86da61cf06',
    messagingSenderId: '1068838387571',
    projectId: 'movil-d4dde',
    authDomain: 'movil-d4dde.firebaseapp.com',
    storageBucket: 'movil-d4dde.firebasestorage.app',
    measurementId: 'G-64K6TTYNRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1uYcUjLhrvESUaD_egFkxdShCeuiqjYc',
    appId: '1:1068838387571:android:d0daeb76ce81f61861cf06',
    messagingSenderId: '1068838387571',
    projectId: 'movil-d4dde',
    storageBucket: 'movil-d4dde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV3KG9wE3QPukwLaB8L6GZKsA8_7nDiNo',
    appId: '1:1068838387571:ios:400fc89239d5c16061cf06',
    messagingSenderId: '1068838387571',
    projectId: 'movil-d4dde',
    storageBucket: 'movil-d4dde.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinalFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV3KG9wE3QPukwLaB8L6GZKsA8_7nDiNo',
    appId: '1:1068838387571:ios:400fc89239d5c16061cf06',
    messagingSenderId: '1068838387571',
    projectId: 'movil-d4dde',
    storageBucket: 'movil-d4dde.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinalFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyuEzBrb9ZA_2Jrse2XD9yBqBGIVRR2us',
    appId: '1:1068838387571:web:916900add4ff164e61cf06',
    messagingSenderId: '1068838387571',
    projectId: 'movil-d4dde',
    authDomain: 'movil-d4dde.firebaseapp.com',
    storageBucket: 'movil-d4dde.firebasestorage.app',
    measurementId: 'G-9LJ6G2YSVQ',
  );

}